backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: simple

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "List of recipe authors"
        fields:
          - name: "authors"
            label: "Authors"
            label_singular: "Author"
            widget: list
            summary: "{{fields.name}}"
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "Displayed on recipes"
      - name: "groups"
        label: "Groups"
        file: "meta/groups.yml"
        description: "List of recipe Groups"
        fields:
          - name: "groups"
            label: "Groups"
            label_singular: "Group"
            widget: "list"
            summary: "{{fields.name}} ({{fields.slug}})"
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the group"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Group name displayed on the site"
              - label: "Image"
                name: "image"
                required: false
                widget: "image"
                allow_multiple: false
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of recipe tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            summary: "{{fields.name}} ({{fields.slug}})"
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    summary: "{{ group }} | {{ title }}"
    identifier_field: "slug"
    sortable_fields: ["title", "slug", "author", "group"]
    view_groups:
      - label: Group
        field: group
      - label: Author
        field: author
    fields:
      - label: Slug
        name: "slug"
        widget: "string"
      - label: Recipe Name
        name: "title"
        widget: "string"
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
          - "authors.*.slug"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
        options_length: 50
      - label: Group
        name: "group"
        widget: relation
        collection: "meta"
        file: "groups"
        searchFields:
          - "groups.*.name"
          - "groups.*.slug"
        displayFields:
          - "groups.*.name"
        valueField: "groups.*.slug"
        default: "uncategorized"
        options_length: 50
      - label: "Image"
        name: "image"
        required: false
        widget: "image"
        allow_multiple: false
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
          options_length: 100
      - label: "Prep Time"
        name: "prep_time"
        widget: "object"
        summary: "{{fields.time}} {{fields.unit}}"
        fields:
          - label: "Time"
            name: "time"
            widget: "number"
            value_type: "int"
            min: 1
          - label: "Unit"
            name: "unit"
            widget: "select"
            options:
              - { label: "Minute", value: "minute" }
              - { label: "Hour", value: "hour" }
              - { label: "Day", value: "day" }
      - label: "Cook Time"
        name: "cook_time"
        widget: "object"
        summary: "{{fields.time}} {{fields.unit}}"
        fields:
          - label: "Time"
            name: "time"
            widget: "number"
            value_type: "int"
            min: 1
          - label: "Unit"
            name: "unit"
            widget: "select"
            options:
              - { label: "Minute", value: "minute" }
              - { label: "Hour", value: "hour" }
              - { label: "Day", value: "day" }
      - label: "Servings"
        name: "servings"
        widget: "object"
        summary: "{{fields.minimum}} - {{fields.maximum}}"
        fields:
          - label: "Minimum"
            name: "minimum"
            widget: "number"
            value_type: "int"
            min: 1
          - label: "Maximum"
            name: "maximum"
            widget: "number"
            value_type: "int"
            min: 1
            required: false
      - label: "Pre Recipe Notes"
        name: "pre_recipe_notes"
        required: false
        widget: "markdown"
        buttons:
          - "bold"
          - "italic"
          - "link"
          - "quote"
          - "bulleted-list"
          - "numbered-list"
        editor_components: ["image"]
        sanitize_preview: true
      - label: "Materials"
        name: "materials"
        required: false
        widget: "list"
        label_singular: "material"
        fields:
          - label: "Item"
            name: "item"
            widget: "string"
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        label_singular: "ingredient"
        fields:
          - label: "Item"
            name: "item"
            widget: "string"
          - label: "Substitute"
            name: "substitute"
            required: false
            widget: "string"
      - label: "Directions"
        name: "directions"
        widget: "list"
        label_singular: "direction"
        fields:
          - label: "Step"
            name: "step"
            widget: "markdown"
            buttons:
              - "bold"
              - "italic"
              - "link"
              - "quote"
              - "bulleted-list"
              - "numbered-list"
            editor_components: ["image"]
            sanitize_preview: true
          - label: "Ingredients"
            name: "ingredients"
            required: false
            widget: "list"
            label_singular: "ingredient"
            fields:
              - label: "Item"
                name: "item"
                widget: "string"
      - label: "Post Recipe Notes"
        name: "post_recipe_notes"
        required: false
        widget: "markdown"
        buttons:
          - "bold"
          - "italic"
          - "link"
          - "quote"
          - "bulleted-list"
          - "numbered-list"
        editor_components: ["image"]
        sanitize_preview: true
